<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales2026/blob/main/Semana9/GaussJordan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [26]:
A = np.array([[3.,-1.,-1.],[-1.,3.,1.],[2.,1.,4.]])
A

array([[ 3., -1., -1.],
       [-1.,  3.,  1.],
       [ 2.,  1.,  4.]])

In [27]:
b = np.array([1.,3.,7.])
b

array([1., 3., 7.])

In [28]:
np.linalg.solve(A,b)

array([1., 1., 1.])

In [29]:
def TriangularSuperior(A,b=None):

  A = np.array(A, dtype=float, copy=True)
  n = A.shape[0]
  y = None if b is None else np.array(b, dtype=float, copy=True)
  print(y)
  # k es la coordenada k
  for k in range(n):
    #print(k)
    if A[k,k] == 0:
      raise ValueError("La matriz problematica")
    else:
      pivote = A[k,k]
      for i in range(k+1,n):
        m_i_k = A[i,k]/pivote
        # Restamos a la fila j, el m_ik por la fija j
        A[i, k:] = A[i, k:] - m_i_k*A[k,k:]
        if y is not None:
          y[i] = y[i] - m_i_k*y[k]

  return (A,y) if b is not None else A

In [30]:
U,y = TriangularSuperior(A,b)

[1. 3. 7.]


In [31]:
y

array([1.        , 3.33333333, 4.25      ])