<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales2026/blob/main/Semana9/GaussJordan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
b = np.array([1.,3.,7.])
A

array([[ 3., -1., -1.],
       [-1.,  3.,  1.],
       [ 2.,  1.,  4.]])

In [3]:
xsol = np.linalg.solve(A,b)
xsol

array([1., 1., 1.])

In [6]:
def TriangularSuperior(A,b=None):

  A = np.array(A, dtype=float, copy=True)
  n = A.shape[0]

  y = None if b is None else np.array(b, dtype=float, copy =True)

  print(y)

  return (A,y) if b is not None else A

In [7]:
TriangularSuperior(A)

None


array([[ 3., -1., -1.],
       [-1.,  3.,  1.],
       [ 2.,  1.,  4.]])