<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales2026/blob/main/Semana9/GaussJordan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
b = np.array([1.,3.,7.])
A

array([[ 3., -1., -1.],
       [-1.,  3.,  1.],
       [ 2.,  1.,  4.]])

In [3]:
xsol = np.linalg.solve(A,b)
xsol

array([1., 1., 1.])

In [13]:
def TriangularSuperior(A,b=None):

  A = np.array(A, dtype=float, copy=True)
  n = A.shape[0]

  y = None if b is None else np.array(b, dtype=float, copy =True)

  print(y)

  # VOlver triangular superior
  # Iteramos sobre las filas
  for k in range(n):
    print(k)
    if A[k,k] == 0:
      raise ValueError("NO creemos que gemini sepa todo: pueden haber problemas con la matriz")
    else:
      pivote = A[k,k]
      # Iteramos sobre las columnas
      for i in range(k+1,n):
        print(k,i)
        m_i_k = A[i,k]/pivote
        print('El factor es:', m_i_k)
        # restamos a la fila j, el mik por la fila i
        print('antes',A[i,:])
        A[i, k:] = A[i, k:] - m_i_k*A[k, k:]
        print('despues',A[i,:])
        if b is not None:
          y[i] = y[i] - m_i_k*y[k]

  return (A,y) if b is not None else A

In [17]:
A1, b1 = TriangularSuperior(A,b)

[1. 3. 7.]
0
0 1
El factor es: -0.3333333333333333
antes [-1.  3.  1.]
despues [0.         2.66666667 0.66666667]
0 2
El factor es: 0.6666666666666666
antes [2. 1. 4.]
despues [0.         1.66666667 4.66666667]
1
1 2
El factor es: 0.625
antes [0.         1.66666667 4.66666667]
despues [0.   0.   4.25]
2


In [18]:
A1

array([[ 3.        , -1.        , -1.        ],
       [ 0.        ,  2.66666667,  0.66666667],
       [ 0.        ,  0.        ,  4.25      ]])

In [19]:
b1

array([1.        , 3.33333333, 4.25      ])

In [24]:
# Aca guardamos la solucion
x = np.zeros_like(b1)
x

array([0., 0., 0.])

In [26]:
n = b1.shape[0]
#print(n)
for i in reversed(range(n)):
  #print(i)

  x[i] = b1[i]

  for j in range(i+1,n):
    x[i] -= A1[i,j]*x[j]

  x[i] /= A1[i,i]

print(x)

[1. 1. 1.]
