<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales2026/blob/main/Semana9/GaussJordan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
A = np.array([[3.,-1.,-1.],[-1.,3.,1.],[2.,1.,4.]])
A

array([[ 3., -1., -1.],
       [-1.,  3.,  1.],
       [ 2.,  1.,  4.]])

In [4]:
b = np.array([1.,3.,7.])
b

array([1., 3., 7.])

In [5]:
np.linalg.solve(A,b)

array([1., 1., 1.])