<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales2026/blob/main/Semana6/CuadraturaGaussLaguerre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.special import factorial
import sympy as sym

In [3]:
def GetNewtonMethod(f,df,xn,itmax = 1000, precision=1e-14):

    error = 1.
    it = 0

    while error >= precision and it < itmax:

      dfx = df(xn)

      # Evitar división por cero
      if np.abs(dfx) < 1e-16:
            print("Derivada cercana a cero. Método falla.")
            return False

      xn1 = xn - f(xn)/df(xn)
      error = np.abs( xn1-xn )

      xn  = xn1
      it += 1


    if it == itmax:
        return False
    else:
        return xn

In [4]:
def GetAllRoots(f, df, x, tolerancia_decimales=8, tol_unicidad=1e-6):

    Roots = []

    for x0 in x:

        root = GetNewtonMethod(f, df, x0)

        if root is not False:

            # Redondeamos
            croot = np.round(root, tolerancia_decimales)

            # Verificamos que no esté ya (con tolerancia)
            if not any(np.isclose(croot, r, atol=tol_unicidad) for r in Roots):
                Roots.append(croot)

    Roots = np.array(Roots)
    Roots.sort()

    return Roots

In [5]:
x = sym.Symbol('x',Real=True)

In [6]:
def GetLaguerre(n):

    y = sym.exp(-x) * x**n
    p = sym.exp(x) * sym.diff(y, x, n) / factorial(n)

    return p

In [7]:
Laguerre = []
DLaguerre = []

n=5

for i in range(n+1):

    p = GetLaguerre(i)
    dp = sym.diff(p,x)

    Laguerre.append(p)
    DLaguerre.append(dp)

In [8]:
Laguerre[n]

-0.00833333333333333*x**5 + 0.208333333333333*x**4 - 1.66666666666667*x**3 + 5.0*x**2 - 5.0*x + 1.0

In [9]:
DLaguerre[n]

-0.0416666666666667*x**4 + 0.833333333333333*x**3 - 5.0*x**2 + 10.0*x - 5.0

In [10]:
def GetRootsPolynomial(n,xi,poly,dpoly):


    pn = sym.lambdify([x],poly[n],'numpy')
    dpn = sym.lambdify([x],dpoly[n],'numpy')

    Roots = GetAllRoots(pn,dpn,xi)

    return Roots

In [11]:
xi = np.linspace(1,50,100,dtype=np.longdouble)
Roots = GetRootsPolynomial(n,xi,Laguerre,DLaguerre)
Roots

array([ 0.26356032,  1.41340306,  3.59642577,  7.08581001, 12.64080084],
      dtype=float128)

In [12]:
F = sym.exp(-x)*x**3
F

x**3*exp(-x)

In [13]:
sym.integrate(F,(x,0,sym.oo))

6

In [28]:
# Usando cuadratura de laguerre
Roots, Weights = np.polynomial.laguerre.laggauss(20)
Roots, Weights

(array([ 0.07053989,  0.37212682,  0.9165821 ,  1.70730653,  2.74919926,
         4.04892531,  5.61517497,  7.45901745,  9.59439287, 12.03880255,
        14.81429344, 17.94889552, 21.47878824, 25.45170279, 29.93255463,
        35.01343424, 40.83305706, 47.61999405, 55.81079575, 66.52441653]),
 array([1.68746802e-01, 2.91254362e-01, 2.66686103e-01, 1.66002453e-01,
        7.48260647e-02, 2.49644173e-02, 6.20255084e-03, 1.14496239e-03,
        1.55741773e-04, 1.54014409e-05, 1.08648637e-06, 5.33012091e-08,
        1.75798118e-09, 3.72550240e-11, 4.76752925e-13, 3.37284424e-15,
        1.15501434e-17, 1.53952214e-20, 5.28644273e-24, 1.65645661e-28]))

In [29]:
f = lambda x: x**3 / (1-np.exp(-x))

In [30]:
x = np.linspace(0,10,100)
y = f(x)

/tmp/ipython-input-534/3109959433.py:1: RuntimeWarning: invalid value encountered in divide
  f = lambda x: x**3 / (1-np.exp(-x))


In [31]:
#plt.plot(x,y)

In [32]:
I = np.sum(Weights*f(Roots))
I

np.float64(6.493939402219589)

In [33]:
np.pi**4/15

6.493939402266828

In [15]:
f = lambda x: x**3

In [16]:
I = np.sum( Weights*f(Roots) )
I

np.float64(6.000000000000005)