<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales2026/blob/main/Semana6/CuadraturaGauss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.special import factorial
import sympy as sym

In [2]:
f = lambda x: 6*x**2

In [3]:
W = np.array([1.,1.])
X = np.array([-1./np.sqrt(3),1./np.sqrt(3)])

In [4]:
I = np.sum(W*f(X))
I

np.float64(4.000000000000001)

In [5]:
I = np.sin(1) - np.sin(-1)
I

np.float64(1.682941969615793)

In [11]:
np.sum(W*np.cos(X))

np.float64(1.6758236553899861)

In [12]:
def GetNewtonMethod(f,df,xn,itmax = 1000, precision=1e-14):

    error = 1.
    it = 0

    while error >= precision and it < itmax:

      dfx = df(xn)

      # Evitar división por cero
      if np.abs(dfx) < 1e-16:
            print("Derivada cercana a cero. Método falla.")
            return False

      xn1 = xn - f(xn)/df(xn)
      error = np.abs( xn1-xn )

      xn  = xn1
      it += 1


    if it == itmax:
        return False
    else:
        return xn

In [13]:
def GetAllRoots(f, df, x, tolerancia_decimales=8, tol_unicidad=1e-6):

    Roots = []

    for x0 in x:

        root = GetNewtonMethod(f, df, x0)

        if root is not False:

            # Redondeamos
            croot = np.round(root, tolerancia_decimales)

            # Verificamos que no esté ya (con tolerancia)
            if not any(np.isclose(croot, r, atol=tol_unicidad) for r in Roots):
                Roots.append(croot)

    Roots = np.array(Roots)
    Roots.sort()

    return Roots

In [14]:
def GetLegendre(n):

  x = sym.Symbol('x',Real=True)
  #y = sym.Symbol('y',Real=True)

  y = (x**2 - 1)**n

  p = sym.diff(y,x,n)/(2**n * factorial(n))

  return p

In [25]:
GetLegendre(5)

0.125*x*(8*x**4 + 40*x**2*(x**2 - 1) + 15*(x**2 - 1)**2)

In [35]:
Legendre = []
DLegendre = []

x = sym.Symbol('x',Real=True)
n=20

for i in range(n+1):

    poly = GetLegendre(i)

    Legendre.append(poly)
    DLegendre.append(sym.diff(poly,x))

In [36]:
Legendre[n]

1.0*x**20 + 95.0*x**18*(x**2 - 1) + 1816.875*x**16*(x**2 - 1)**2 + 12112.5*x**14*(x**2 - 1)**3 + 34444.921875*x**12*(x**2 - 1)**4 + 45467.296875*x**10*(x**2 - 1)**5 + 28417.060546875*x**8*(x**2 - 1)**6 + 8119.16015625*x**6*(x**2 - 1)**7 + 951.464080810547*x**4*(x**2 - 1)**8 + 35.2394104003906*x**2*(x**2 - 1)**9 + 0.176197052001953*(x**2 - 1)**10

In [37]:
def GetRootsPolynomial(n,xi,poly,dpoly):

    x = sym.Symbol('x',Real=True)
    pn = sym.lambdify([x],poly[n],'numpy')
    dpn = sym.lambdify([x],dpoly[n],'numpy')

    Roots = GetAllRoots(pn,dpn,xi)

    return Roots

In [38]:
xi = np.linspace(-1.,1,100,dtype=np.longdouble)
Roots = GetRootsPolynomial(n,xi,Legendre,DLegendre)
Roots

array([-0.9931286 , -0.96397193, -0.91223443, -0.83911697, -0.74633191,
       -0.63605368, -0.510867  , -0.37370609, -0.22778585, -0.07652652,
        0.07652652,  0.22778585,  0.37370609,  0.510867  ,  0.63605368,
        0.74633191,  0.83911697,  0.91223443,  0.96397193,  0.9931286 ],
      dtype=float128)

In [39]:
# Calculando usando el paquete
a = 0
b = 0.25*np.pi
f = lambda x: np.sin(x)

In [43]:
Roots, Weights = np.polynomial.legendre.leggauss(7)
t = 0.5*( (b-a)*Roots + b + a )
Integral = 0.5*(b-a)*np.sum(Weights*f(t))
Roots

array([-0.94910791, -0.74153119, -0.40584515,  0.        ,  0.40584515,
        0.74153119,  0.94910791])

In [44]:
Weights

array([0.12948497, 0.27970539, 0.38183005, 0.41795918, 0.38183005,
       0.27970539, 0.12948497])

In [45]:
print('{:.70f}'.format(Integral))
print('{:.70f}'.format(1-np.cos(0.25*np.pi)))

0.2928932188134524272626890706305857747793197631835937500000000000000000
0.2928932188134524272626890706305857747793197631835937500000000000000000
