<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales2026/blob/main/Semana6/CuadraturaGauss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.special import factorial
import sympy as sym

In [ ]:
def GetNewtonMethod(f,df,xn,itmax = 1000, precision=1e-14):

    error = 1.
    it = 0

    while error >= precision and it < itmax:

      dfx = df(xn)

      # Evitar división por cero
      if np.abs(dfx) < 1e-16:
            print("Derivada cercana a cero. Método falla.")
            return False

      xn1 = xn - f(xn)/df(xn)
      error = np.abs( xn1-xn )

      xn  = xn1
      it += 1


    if it == itmax:
        return False
    else:
        return xn

In [ ]:
def GetAllRoots(f, df, x, tolerancia_decimales=8, tol_unicidad=1e-6):

    Roots = []

    for x0 in x:

        root = GetNewtonMethod(f, df, x0)

        if root is not False:

            # Redondeamos
            croot = np.round(root, tolerancia_decimales)

            # Verificamos que no esté ya (con tolerancia)
            if not any(np.isclose(croot, r, atol=tol_unicidad) for r in Roots):
                Roots.append(croot)

    Roots = np.array(Roots)
    Roots.sort()

    return Roots

In [ ]:
def GetLegendre(n):

  x = sym.Symbol('x',Real=True)
  y = sym.Symbol('y',Real=True)

  y = (x**2 - 1)**n

  p = sym.diff(y,x,n)/(2**n * factorial(n))

  return p

In [ ]:
Legendre = []
DLegendre = []

x = sym.Symbol('x',Real=True)
n=3

for i in range(n+1):

    poly = GetLegendre(i)

    Legendre.append(poly)
    DLegendre.append(sym.diff(poly,x))

In [ ]:
Legendre[n]

0.5*x*(5*x**2 - 3)

In [ ]:
def GetRootsPolynomial(n,xi,poly,dpoly):

    x = sym.Symbol('x',Real=True)
    pn = sym.lambdify([x],poly[n],'numpy')
    dpn = sym.lambdify([x],dpoly[n],'numpy')

    Roots = GetAllRoots(pn,dpn,xi)

    return Roots

In [ ]:
xi = np.linspace(-1.,1,100,dtype=np.longdouble)
Roots = GetRootsPolynomial(n,xi,Legendre,DLegendre)
Roots

array([-0.77459667,  0.        ,  0.77459667], dtype=float128)

In [ ]:
# Calculando usando el paquete
a = 0
b = 0.25*np.pi
f = lambda x: np.sin(x)

In [ ]:
Roots, Weights = np.polynomial.legendre.leggauss(3)
t = 0.5*( (b-a)*Roots + b + a )
Integral = 0.5*(b-a)*np.sum(Weights*f(t))
Roots

array([-0.77459667,  0.        ,  0.77459667])

In [ ]:
Weights

array([0.55555556, 0.88888889, 0.55555556])

In [ ]:
print('{:.70f}'.format(Integral))
print('{:.70f}'.format(1-np.cos(0.25*np.pi)))

0.2928932536416773979581762432644609361886978149414062500000000000000000
0.2928932188134524272626890706305857747793197631835937500000000000000000
